// The foods `cook calorie` knows, picked from the USDA National Nutrient
// Database for Standard Reference, Release 28 (SR28). Each is
//   [NDB number, name, state, extra search words]
// under its group. The NDB number is also how the food is found in USDA
// FoodData Central (data type "SR Legacy"), to check or update it.
// tools/build-nutrition.mjs turns this list into js/lib/nutrition-data.js.

export const FOODS = {
  Poultry: [
    ['05062', 'Chicken breast, skinless', 'raw', 'fillet'],
    ['05064', 'Chicken breast, skinless', 'roasted', 'fillet baked'],
    ['05747', 'Chicken breast, skinless', 'grilled', 'fillet'],
    ['05063', 'Chicken breast, skinless', 'fried', 'fillet'],
    ['05057', 'Chicken breast with skin', 'raw', ''],
    ['05060', 'Chicken breast with skin', 'roasted', 'baked'],
    ['05096', 'Chicken thigh, skinless', 'raw', 'dark meat'],
    ['05098', 'Chicken thigh, skinless', 'roasted', 'dark meat baked'],
    ['05094', 'Chicken thigh with skin', 'roasted', 'dark meat baked'],
    ['05071', 'Chicken drumstick, skinless', 'raw', 'leg dark meat'],
    ['05073', 'Chicken drumstick, skinless', 'roasted', 'leg dark meat baked'],
    ['05066', 'Chicken drumstick with skin', 'raw', 'leg'],
    ['05069', 'Chicken drumstick with skin', 'roasted', 'leg baked'],
    ['05100', 'Chicken wings with skin', 'raw', 'wing'],
    ['05103', 'Chicken wings with skin', 'roasted', 'wing baked'],
    ['05101', 'Chicken wings with skin', 'fried in batter', 'wing'],
    ['05006', 'Chicken, whole, meat and skin', 'raw', 'bird'],
    ['05009', 'Chicken, whole, meat and skin', 'roasted', 'bird rotisserie'],
    ['05332', 'Chicken mince', 'raw', 'ground minced'],
    ['05333', 'Chicken mince', 'pan-browned', 'ground minced'],
    ['05027', 'Chicken liver', 'raw', 'offal'],
    ['05028', 'Chicken liver', 'simmered', 'offal'],
    ['05219', 'Turkey breast, skinless', 'raw', ''],
    ['05220', 'Turkey breast, skinless', 'roasted', ''],
    ['05187', 'Turkey dark meat, skinless', 'raw', 'thigh leg'],
    ['05665', 'Turkey mince, 93% lean', 'raw', 'ground minced'],
    ['05666', 'Turkey mince, 93% lean', 'pan-browned', 'ground minced'],
    ['05141', 'Duck, meat only', 'raw', ''],
    ['05142', 'Duck, meat only', 'roasted', ''],
    ['05140', 'Duck, meat and skin', 'roasted', ''],
  ],
  Beef: [
    ['23557', 'Beef mince, 5% fat', 'raw', 'ground minced lean'],
    ['23560', 'Beef mince, 5% fat', 'pan-browned', 'ground minced lean'],
    ['23562', 'Beef mince, 10% fat', 'raw', 'ground minced'],
    ['23565', 'Beef mince, 10% fat', 'pan-browned', 'ground minced'],
    ['23567', 'Beef mince, 15% fat', 'raw', 'ground minced'],
    ['23570', 'Beef mince, 15% fat', 'pan-browned', 'ground minced'],
    ['23572', 'Beef mince, 20% fat', 'raw', 'ground minced'],
    ['23573', 'Beef mince, 20% fat', 'grilled patty', 'ground minced burger'],
    ['23575', 'Beef mince, 20% fat', 'pan-browned', 'ground minced'],
    ['23625', 'Beef sirloin steak, lean', 'raw', 'steak'],
    ['13455', 'Beef sirloin steak, lean', 'grilled', 'steak broiled'],
    ['23202', 'Beef ribeye steak, with fat', 'raw', 'steak rib eye entrecote'],
    ['23195', 'Beef ribeye steak, with fat', 'grilled', 'steak rib eye entrecote'],
    ['23624', 'Beef fillet (tenderloin), lean', 'raw', 'steak filet mignon'],
    ['23600', 'Beef fillet (tenderloin), lean', 'grilled', 'steak filet mignon broiled'],
    ['13235', 'Beef T-bone steak, lean', 'raw', 'steak'],
    ['13236', 'Beef T-bone steak, lean', 'grilled', 'steak'],
    ['23361', 'Beef eye of round, lean', 'raw', 'roast topside silverside'],
    ['13419', 'Beef eye of round, lean', 'roasted', 'roast topside silverside'],
    ['13596', 'Beef brisket, lean', 'raw', ''],
    ['13343', 'Beef brisket, lean', 'braised', 'slow'],
    ['13294', 'Beef chuck, lean', 'raw', 'stewing braising'],
    ['13377', 'Beef chuck, lean', 'braised', 'stew pot roast'],
    ['13325', 'Beef liver', 'raw', 'offal'],
    ['13327', 'Beef liver', 'pan-fried', 'offal'],
  ],
  Pork: [
    ['10024', 'Pork loin, lean', 'raw', 'chop roast'],
    ['10027', 'Pork loin, lean', 'roasted', 'chop roast'],
    ['10050', 'Pork chop, lean', 'grilled', 'loin broiled'],
    ['10060', 'Pork tenderloin, lean', 'raw', 'fillet'],
    ['10061', 'Pork tenderloin, lean', 'roasted', 'fillet'],
    ['10084', 'Pork shoulder, lean', 'raw', 'butt collar'],
    ['10085', 'Pork shoulder, lean', 'braised', 'butt collar pulled'],
    ['10219', 'Pork mince', 'raw', 'ground minced'],
    ['10220', 'Pork mince', 'cooked', 'ground minced'],
    ['10088', 'Pork spareribs', 'raw', 'ribs'],
    ['10940', 'Pork spareribs', 'roasted', 'ribs'],
    ['10123', 'Bacon', 'raw', 'pork streaky'],
    ['10862', 'Bacon', 'pan-fried', 'pork streaky crispy'],
    ['10183', 'Ham, cooked', 'ready to eat', 'pork gammon'],
    ['07029', 'Ham, sliced', 'ready to eat', 'pork deli lunch meat'],
  ],
  'Lamb and veal': [
    ['17013', 'Lamb leg, lean', 'raw', ''],
    ['17014', 'Lamb leg, lean', 'roasted', ''],
    ['17026', 'Lamb loin, lean', 'raw', 'chop'],
    ['17027', 'Lamb loin, lean', 'grilled', 'chop broiled'],
    ['17224', 'Lamb mince', 'raw', 'ground minced'],
    ['17225', 'Lamb mince', 'grilled', 'ground minced broiled'],
    ['17142', 'Veal mince', 'raw', 'ground minced'],
    ['17143', 'Veal mince', 'grilled', 'ground minced broiled'],
  ],
  'Sausages and cured meat': [
    ['07063', 'Pork sausages', 'raw', 'sausage bangers'],
    ['07064', 'Pork sausages', 'pan-fried', 'sausage bangers'],
    ['07036', 'Italian sausage, pork', 'raw', 'sausage'],
    ['07089', 'Italian sausage, pork', 'cooked', 'sausage'],
    ['07022', 'Frankfurter (hot dog), beef', 'ready to eat', 'sausage wiener'],
    ['07059', 'Polish sausage (kielbasa), pork', 'ready to eat', 'sausage'],
    ['07019', 'Chorizo', 'ready to eat', 'sausage'],
    ['07071', 'Salami, dry, pork', 'ready to eat', 'sausage'],
    ['07057', 'Pepperoni', 'ready to eat', 'sausage'],
  ],
  'Fish and seafood': [
    ['15236', 'Salmon, Atlantic, farmed', 'raw', 'fish'],
    ['15237', 'Salmon, Atlantic, farmed', 'baked', 'fish cooked grilled roasted'],
    ['15076', 'Salmon, Atlantic, wild', 'raw', 'fish'],
    ['15209', 'Salmon, Atlantic, wild', 'baked', 'fish cooked grilled roasted'],
    ['15087', 'Salmon, canned', 'drained', 'fish sockeye tinned'],
    ['15015', 'Cod', 'raw', 'fish white'],
    ['15016', 'Cod', 'baked', 'fish white cooked'],
    ['15033', 'Haddock', 'raw', 'fish white'],
    ['15034', 'Haddock', 'baked', 'fish white cooked'],
    ['15261', 'Tilapia', 'raw', 'fish white'],
    ['15262', 'Tilapia', 'baked', 'fish white cooked'],
    ['15091', 'Sea bass', 'raw', 'fish white'],
    ['15092', 'Sea bass', 'baked', 'fish white cooked'],
    ['15240', 'Trout, rainbow', 'raw', 'fish'],
    ['15241', 'Trout, rainbow', 'baked', 'fish cooked'],
    ['15046', 'Mackerel', 'raw', 'fish oily'],
    ['15047', 'Mackerel', 'baked', 'fish oily cooked'],
    ['15039', 'Herring', 'raw', 'fish oily'],
    ['15041', 'Herring, pickled', 'ready to eat', 'fish'],
    ['15127', 'Tuna, fresh (yellowfin)', 'raw', 'fish steak'],
    ['15121', 'Tuna, canned in water', 'drained', 'fish tinned brine'],
    ['15119', 'Tuna, canned in oil', 'drained', 'fish tinned'],
    ['15088', 'Sardines, canned in oil', 'drained', 'fish tinned'],
    ['15149', 'Shrimp (prawns)', 'raw', 'prawn seafood'],
    ['15151', 'Shrimp (prawns)', 'boiled', 'prawn seafood cooked'],
    ['15164', 'Mussels', 'raw', 'seafood shellfish'],
    ['15165', 'Mussels', 'steamed', 'seafood shellfish cooked'],
    ['15175', 'Squid (calamari)', 'raw', 'seafood'],
    ['15176', 'Squid (calamari)', 'fried', 'seafood'],
    ['15172', 'Scallops', 'raw', 'seafood shellfish'],
    ['15140', 'Crab, blue', 'boiled', 'seafood shellfish cooked'],
    ['15027', 'Fish fingers (fish sticks)', 'oven-baked', 'fish breaded frozen'],
  ],
  Eggs: [
    ['01123', 'Egg, whole', 'raw', 'eggs'],
    ['01129', 'Egg, whole', 'hard-boiled', 'eggs boiled'],
    ['01131', 'Egg, whole', 'poached', 'eggs'],
    ['01128', 'Egg, whole', 'fried', 'eggs'],
    ['01132', 'Egg, whole', 'scrambled', 'eggs'],
    ['01130', 'Egg, whole', 'omelette', 'eggs omelet'],
    ['01124', 'Egg white', 'raw', 'eggs'],
    ['01125', 'Egg yolk', 'raw', 'eggs'],
  ],
  Dairy: [
    ['01077', 'Milk, whole (3.25%)', '', 'full fat'],
    ['01079', 'Milk, semi-skimmed (2%)', '', 'reduced fat'],
    ['01082', 'Milk, 1%', '', 'low fat'],
    ['01085', 'Milk, skimmed', '', 'nonfat skim fat free'],
    ['01230', 'Buttermilk', '', 'milk'],
    ['01053', 'Cream, double (heavy)', '', 'whipping'],
    ['01056', 'Sour cream', '', 'cream'],
    ['01001', 'Butter, salted', '', ''],
    ['01145', 'Butter, unsalted', '', ''],
    ['01116', 'Yogurt, plain, whole milk', '', 'yoghurt natural'],
    ['01293', 'Greek yogurt, plain, whole milk', '', 'yoghurt'],
    ['01256', 'Greek yogurt, plain, fat-free', '', 'yoghurt nonfat 0%'],
    ['01121', 'Yogurt, fruit, low-fat', '', 'yoghurt'],
    ['01009', 'Cheddar', '', 'cheese'],
    ['01026', 'Mozzarella', '', 'cheese'],
    ['01033', 'Parmesan', '', 'cheese parmigiano'],
    ['01019', 'Feta', '', 'cheese white brine sirene'],
    ['01040', 'Swiss cheese (Emmental)', '', 'cheese'],
    ['01022', 'Gouda', '', 'cheese'],
    ['01006', 'Brie', '', 'cheese'],
    ['01007', 'Camembert', '', 'cheese'],
    ['01004', 'Blue cheese', '', 'cheese'],
    ['01035', 'Provolone', '', 'cheese'],
    ['01036', 'Ricotta, whole milk', '', 'cheese'],
    ['01017', 'Cream cheese', '', 'cheese philadelphia'],
    ['01012', 'Cottage cheese', '', 'cheese'],
    ['01015', 'Cottage cheese, low-fat (2%)', '', 'cheese'],
    ['19095', 'Ice cream, vanilla', '', 'dessert'],
    ['19270', 'Ice cream, chocolate', '', 'dessert'],
  ],
  'Grains, bread and pasta': [
    ['20044', 'Rice, white, long-grain', 'uncooked', 'basmati jasmine dry'],
    ['20045', 'Rice, white, long-grain', 'boiled', 'basmati jasmine cooked'],
    ['20036', 'Rice, brown', 'uncooked', 'wholegrain dry'],
    ['20037', 'Rice, brown', 'boiled', 'wholegrain cooked'],
    ['20120', 'Pasta', 'dry', 'spaghetti penne macaroni uncooked'],
    ['20121', 'Pasta', 'boiled', 'spaghetti penne macaroni cooked'],
    ['20124', 'Pasta, whole-wheat', 'dry', 'spaghetti wholemeal uncooked'],
    ['20125', 'Pasta, whole-wheat', 'boiled', 'spaghetti wholemeal cooked'],
    ['20109', 'Egg noodles', 'dry', 'uncooked'],
    ['20110', 'Egg noodles', 'boiled', 'cooked'],
    ['20133', 'Rice noodles', 'dry', 'uncooked'],
    ['20134', 'Rice noodles', 'boiled', 'cooked'],
    ['20035', 'Quinoa', 'uncooked', 'dry'],
    ['20137', 'Quinoa', 'boiled', 'cooked'],
    ['20028', 'Couscous', 'dry', 'uncooked'],
    ['20029', 'Couscous', 'cooked', ''],
    ['20012', 'Bulgur', 'dry', 'uncooked'],
    ['20013', 'Bulgur', 'cooked', ''],
    ['20005', 'Barley, pearled', 'uncooked', 'dry'],
    ['20006', 'Barley, pearled', 'boiled', 'cooked'],
    ['20009', 'Buckwheat groats', 'dry', 'kasha uncooked'],
    ['20010', 'Buckwheat groats', 'cooked', 'kasha'],
    ['08120', 'Oats, rolled', 'dry', 'oatmeal porridge uncooked'],
    ['08121', 'Porridge (oats cooked with water)', 'cooked', 'oatmeal'],
    ['20081', 'Flour, white (all-purpose)', '', 'plain wheat'],
    ['20080', 'Flour, wholemeal', '', 'whole wheat whole-grain'],
    ['20022', 'Cornmeal (polenta)', '', 'maize'],
    ['18069', 'Bread, white', '', 'loaf toast sandwich'],
    ['18075', 'Bread, wholemeal', '', 'whole wheat brown loaf'],
    ['18060', 'Bread, rye', '', 'loaf'],
    ['18029', 'Baguette (French bread, sourdough)', '', 'bread'],
    ['18041', 'Pita bread', '', 'bread pitta'],
    ['18001', 'Bagel', '', 'bread'],
    ['18258', 'English muffin', '', 'bread'],
    ['18364', 'Tortilla wrap, flour', '', 'wrap bread'],
    ['18363', 'Tortilla, corn', '', 'taco'],
    ['18239', 'Croissant, butter', '', 'pastry'],
    ['08020', 'Corn flakes', '', 'cereal breakfast'],
    ['08037', 'Granola', '', 'cereal breakfast muesli'],
  ],
  'Legumes and soy': [
    ['16069', 'Lentils', 'dry', 'uncooked'],
    ['16070', 'Lentils', 'boiled', 'cooked'],
    ['16056', 'Chickpeas', 'dry', 'garbanzo uncooked'],
    ['16057', 'Chickpeas', 'boiled', 'garbanzo cooked'],
    ['16358', 'Chickpeas, canned', 'drained', 'garbanzo tinned'],
    ['16014', 'Black beans', 'dry', 'uncooked'],
    ['16015', 'Black beans', 'boiled', 'cooked'],
    ['16032', 'Kidney beans', 'dry', 'red uncooked'],
    ['16033', 'Kidney beans', 'boiled', 'red cooked'],
    ['16145', 'Kidney beans, canned', 'drained', 'red tinned'],
    ['16049', 'White beans', 'dry', 'cannellini navy haricot uncooked'],
    ['16050', 'White beans', 'boiled', 'cannellini navy haricot cooked'],
    ['16426', 'Tofu, firm', '', 'soy bean curd'],
    ['11212', 'Edamame', 'cooked', 'soy beans'],
    ['11304', 'Peas, green', 'raw', 'garden'],
    ['11313', 'Peas, green, frozen', 'boiled', 'garden cooked'],
    ['16158', 'Hummus', '', 'houmous chickpea dip'],
  ],
  Vegetables: [
    ['11352', 'Potato', 'raw', 'potatoes'],
    ['11367', 'Potato, peeled', 'boiled', 'potatoes cooked'],
    ['11674', 'Potato, with skin', 'baked', 'potatoes jacket cooked'],
    ['11360', 'Chips (French fries), frozen', 'oven-baked', 'potatoes fries'],
    ['11507', 'Sweet potato', 'raw', 'yam'],
    ['11508', 'Sweet potato', 'baked', 'yam cooked'],
    ['11090', 'Broccoli', 'raw', ''],
    ['11091', 'Broccoli', 'boiled', 'cooked'],
    ['11124', 'Carrots', 'raw', 'carrot'],
    ['11125', 'Carrots', 'boiled', 'carrot cooked'],
    ['11457', 'Spinach', 'raw', ''],
    ['11458', 'Spinach', 'boiled', 'cooked'],
    ['11529', 'Tomatoes', 'raw', 'tomato'],
    ['11282', 'Onions', 'raw', 'onion'],
    ['11283', 'Onions', 'boiled', 'onion cooked'],
    ['11215', 'Garlic', 'raw', ''],
    ['11821', 'Peppers, red', 'raw', 'bell pepper capsicum sweet'],
    ['11333', 'Peppers, green', 'raw', 'bell pepper capsicum sweet'],
    ['11205', 'Cucumber', 'raw', ''],
    ['11251', 'Lettuce, romaine', 'raw', 'cos salad'],
    ['11252', 'Lettuce, iceberg', 'raw', 'salad'],
    ['11109', 'Cabbage', 'raw', ''],
    ['11110', 'Cabbage', 'boiled', 'cooked'],
    ['11135', 'Cauliflower', 'raw', ''],
    ['11136', 'Cauliflower', 'boiled', 'cooked'],
    ['11477', 'Courgette (zucchini)', 'raw', 'squash'],
    ['11478', 'Courgette (zucchini)', 'boiled', 'squash cooked'],
    ['11209', 'Aubergine (eggplant)', 'raw', ''],
    ['11210', 'Aubergine (eggplant)', 'boiled', 'cooked'],
    ['11260', 'Mushrooms, white', 'raw', 'button champignon'],
    ['11261', 'Mushrooms, white', 'boiled', 'button champignon cooked'],
    ['11052', 'Green beans', 'raw', 'string snap french'],
    ['11053', 'Green beans', 'boiled', 'string snap french cooked'],
    ['11167', 'Sweetcorn', 'raw', 'corn maize'],
    ['11168', 'Sweetcorn', 'boiled', 'corn maize cooked'],
    ['09037', 'Avocado', 'raw', ''],
    ['11233', 'Kale', 'raw', ''],
    ['11011', 'Asparagus', 'raw', ''],
    ['11012', 'Asparagus', 'boiled', 'cooked'],
    ['11080', 'Beetroot', 'raw', 'beets beet'],
    ['11081', 'Beetroot', 'boiled', 'beets beet cooked'],
    ['11098', 'Brussels sprouts', 'raw', ''],
    ['11099', 'Brussels sprouts', 'boiled', 'cooked'],
    ['11143', 'Celery', 'raw', ''],
    ['11422', 'Pumpkin', 'raw', 'squash'],
    ['11485', 'Butternut squash', 'raw', 'pumpkin'],
    ['11486', 'Butternut squash', 'baked', 'pumpkin cooked'],
    ['11246', 'Leeks', 'raw', 'leek'],
    ['11429', 'Radishes', 'raw', 'radish'],
    ['09193', 'Olives, black', 'canned', 'olive'],
    ['11937', 'Pickled cucumbers (dill)', '', 'gherkins pickles'],
  ],
  Fruit: [
    ['09003', 'Apple', 'raw', 'apples'],
    ['09040', 'Banana', 'raw', 'bananas'],
    ['09200', 'Orange', 'raw', 'oranges'],
    ['09316', 'Strawberries', 'raw', 'berries'],
    ['09050', 'Blueberries', 'raw', 'berries'],
    ['09302', 'Raspberries', 'raw', 'berries'],
    ['09132', 'Grapes', 'raw', ''],
    ['09252', 'Pear', 'raw', 'pears'],
    ['09236', 'Peach', 'raw', 'peaches nectarine'],
    ['09176', 'Mango', 'raw', 'mangoes'],
    ['09266', 'Pineapple', 'raw', ''],
    ['09326', 'Watermelon', 'raw', 'melon'],
    ['09181', 'Melon, cantaloupe', 'raw', ''],
    ['09150', 'Lemon', 'raw', 'lemons'],
    ['09148', 'Kiwi', 'raw', 'kiwifruit'],
    ['09070', 'Cherries', 'raw', 'cherry'],
    ['09279', 'Plums', 'raw', 'plum'],
    ['09021', 'Apricots', 'raw', 'apricot'],
    ['09089', 'Figs', 'raw', 'fig'],
    ['09286', 'Pomegranate', 'raw', ''],
    ['09111', 'Grapefruit', 'raw', ''],
    ['09421', 'Dates, Medjool', 'dried', 'date'],
    ['09298', 'Raisins', 'dried', 'sultanas'],
    ['09032', 'Apricots', 'dried', 'apricot'],
    ['09291', 'Prunes', 'dried', 'plums'],
    ['12104', 'Coconut', 'raw', 'flesh meat'],
  ],
  'Nuts and seeds': [
    ['12061', 'Almonds', 'raw', 'nuts'],
    ['12063', 'Almonds', 'dry-roasted', 'nuts'],
    ['12155', 'Walnuts', 'raw', 'nuts'],
    ['12087', 'Cashews', 'raw', 'nuts'],
    ['12120', 'Hazelnuts', 'raw', 'nuts filberts'],
    ['12151', 'Pistachios', 'raw', 'nuts'],
    ['12142', 'Pecans', 'raw', 'nuts'],
    ['12131', 'Macadamias', 'raw', 'nuts'],
    ['12078', 'Brazil nuts', 'raw', 'nuts'],
    ['16087', 'Peanuts', 'raw', 'nuts groundnuts'],
    ['16398', 'Peanut butter, smooth', '', 'nut'],
    ['12036', 'Sunflower seeds', '', 'kernels'],
    ['12014', 'Pumpkin seeds', '', 'pepitas kernels'],
    ['12006', 'Chia seeds', '', ''],
    ['12220', 'Flaxseed (linseed)', '', 'flax seeds'],
    ['12023', 'Sesame seeds', '', ''],
  ],
  'Fats and oils': [
    ['04053', 'Olive oil', '', 'oil extra virgin'],
    ['04060', 'Sunflower oil', '', 'oil vegetable'],
    ['04582', 'Rapeseed oil (canola)', '', 'oil vegetable'],
    ['04047', 'Coconut oil', '', 'oil'],
    ['04002', 'Lard', '', 'fat pork'],
    ['04610', 'Margarine (80% fat)', '', 'spread'],
    ['04025', 'Mayonnaise', '', 'mayo dressing'],
  ],
  'Sugar and spreads': [
    ['19335', 'Sugar, white', '', 'granulated caster table'],
    ['19334', 'Sugar, brown', '', ''],
    ['19336', 'Icing sugar', '', 'powdered confectioners'],
    ['19296', 'Honey', '', ''],
    ['19353', 'Maple syrup', '', 'syrup'],
    ['19297', 'Jam', '', 'preserves jelly'],
    ['19125', 'Chocolate hazelnut spread', '', 'nutella'],
  ],
  'Snacks and sweets': [
    ['19411', 'Potato crisps (chips)', '', 'crisps chips bag'],
    ['19056', 'Tortilla chips', '', 'nachos corn chips'],
    ['19034', 'Popcorn, air-popped', '', ''],
    ['19807', 'Popcorn, oil-popped, salted', '', ''],
    ['19047', 'Pretzels, salted', '', ''],
    ['19816', 'Rice cakes', '', ''],
    ['18228', 'Crackers (saltines)', '', 'cracker'],
    ['19120', 'Milk chocolate', '', 'chocolate bar'],
    ['19903', 'Dark chocolate, 60–69%', '', 'chocolate bar'],
    ['19904', 'Dark chocolate, 70–85%', '', 'chocolate bar'],
    ['19087', 'White chocolate', '', 'chocolate bar'],
    ['19155', 'Snickers', '', 'chocolate bar candy'],
    ['19109', 'KitKat', '', 'chocolate bar wafer candy'],
    ['19141', "M&M's, milk chocolate", '', 'chocolate candy sweets'],
    ['19140', "M&M's, peanut", '', 'chocolate candy sweets'],
    ['19106', 'Gummy sweets (gumdrops)', '', 'gummies candy jelly'],
    ['19107', 'Hard sweets (boiled sweets)', '', 'candy'],
    ['18159', 'Chocolate chip cookies', '', 'biscuits'],
    ['18178', 'Oatmeal cookies', '', 'biscuits'],
    ['18155', 'Butter cookies', '', 'biscuits shortbread'],
    ['18248', 'Doughnut, plain', '', 'donut'],
    ['18096', 'Chocolate cake with frosting', '', 'cake'],
    ['18274', 'Blueberry muffin', '', 'cake'],
    ['18301', 'Apple pie', '', 'pastry'],
  ],
  Drinks: [
    ['09206', 'Orange juice, fresh', '', 'juice'],
    ['09016', 'Apple juice', '', 'juice'],
    ['14148', 'Cola', '', 'soda soft drink coke pop'],
    ['14003', 'Beer', '', 'lager alcohol'],
    ['14096', 'Wine, red', '', 'alcohol'],
    ['14106', 'Wine, white', '', 'alcohol'],
    ['14037', 'Spirits, 40% (vodka, gin, rum, whisky)', '', 'alcohol liquor'],
    ['14209', 'Coffee, black', '', 'brewed'],
    ['14355', 'Tea, black', '', 'brewed'],
    ['14091', 'Almond milk, unsweetened', '', 'plant milk'],
    ['16120', 'Soy milk', '', 'plant milk soya'],
  ],
  'Sauces and condiments': [
    ['11935', 'Ketchup', '', 'catsup tomato sauce'],
    ['02046', 'Mustard, yellow', '', ''],
    ['16123', 'Soy sauce', '', 'shoyu'],
    ['06931', 'Tomato pasta sauce (marinara)', '', 'passata'],
    ['06164', 'Salsa', '', ''],
    ['02069', 'Balsamic vinegar', '', 'vinegar'],
    ['02047', 'Salt', '', 'table'],
  ],
  'Ready meals and fast food': [
    ['21224', 'Pizza, cheese, frozen', 'baked', ''],
    ['21237', 'Big Mac (McDonald\'s)', '', 'burger hamburger fast food'],
    ['21238', 'French fries (McDonald\'s)', '', 'chips fries fast food'],
    ['21108', 'Hamburger with condiments', '', 'burger fast food'],
  ],
};
